Web/Web/Models/AspNetRoles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRoles()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}

Web/Web/Controllers/AspNetRolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
//    [Authorize(Roles = "Administradores")]
    public class AspNetRolesController : Controller
    {
        private entre_rodasEntities db = new entre_rodasEntities();

        // GET: AspNetRoles
        public ActionResult Index(string Pesquisar = "")
        {
            var query = db.AspNetRoles.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisar))
            {
                query = query.Where(c => c.Name.Contains(Pesquisar));
            }
            query = query.OrderBy(c => c.Name);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_AspNetRoles", query.ToList());
            }
            return View(query.ToList());
        }

        // GET: AspNetRoles/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetRoles/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                AspNetRoles role = new AspNetRoles();
                role.Name = aspNetRoles.Name.Trim();
                db.AspNetRoles.Add(role);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }

            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            AspNetRoles role = new AspNetRoles();
            role.Id = aspNetRoles.Id;
            role.Name = aspNetRoles.Name.Trim();
            return View(role);
        }

        // POST: AspNetRoles/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                AspNetRoles role = new AspNetRoles();
                role.Id = aspNetRoles.Id;
                role.Name = aspNetRoles.Name.Trim();
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: AspNetRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRoles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Web/Views/AspNetRoles/Create.cshtml
@model Web.Models.AspNetRoles

@{
    ViewBag.Title = "Perfis de  usuários";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.MenuAtual = "PerfilDeUsuario";
}

<h2>Cadastrar novo perfil de usuário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.Label("Descrição:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span> Salvar
        </button>
        <a href="/AspNetRoles/Index" class="btn btn-primary btn-danger">
            <span class="glyphicon glyphicon-remove"></span>
            Cancelar
        </a>
    </div>
}

Web/Web/Views/AspNetRoles/Delete.cshtml
@model Web.Models.AspNetRoles

@{
    ViewBag.Title = "Perfis de  usuários";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.MenuAtual = "PerfilDeUsuario";
}

<h2>Excluir perfil de usuário</h2>

<div>
    <hr />
    @if (Model.AspNetUsers.Count > 0)
    {
        <div class="alert alert-danger" role="alert">
            Este perfil não pode ser excluído pois existem usúarios relacionado à ele!
        </div>
    }
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Descrição:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div>
            @if (Model.AspNetUsers.Count == 0)
            {
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-trash"></span> Excluir
                </button>
            }
            <a href="/AspNetRoles/Details/@Model.Id" class="btn btn-primary btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
                Cancelar
            </a>
        </div>
    }
</div>

Web/Web/Views/AspNetRoles/Details.cshtml
@model Web.Models.AspNetRoles

@{
    ViewBag.Title = "Perfis de  usuários";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.MenuAtual = "PerfilDeUsuario";
}

<h2>Detalhes do perfil de usuário</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Descrição:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<hr />
<div>
    <a href="/AspNetRoles/Edit/@Model.Id" class="btn btn-primary btn-primary">
        <span class="glyphicon glyphicon-pencil"></span>
        Editar cliente
    </a>
    <a href="/AspNetRoles/Delete/@Model.Id" class="btn btn-primary btn-danger">
        <span class="glyphicon glyphicon-trash"></span>
        Excluir cliente
    </a>
    <a href="/AspNetRoles/Index" class="btn btn-primary btn-warning">
        <span class="glyphicon glyphicon-chevron-left"></span>
        Voltar
    </a>
</div>

Web/Web/Views/AspNetRoles/Edit.cshtml
@model Web.Models.AspNetRoles

@{
    ViewBag.Title = "Perfis de  usuários";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.MenuAtual = "PerfilDeUsuario";
}

<h2>Editar perfil de usuário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.Label("Descrição:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    </div>

    <div>
        <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span> Salvar
        </button>
        <a href="/AspNetRoles/Index" class="btn btn-primary btn-danger">
            <span class="glyphicon glyphicon-remove"></span>
            Cancelar
        </a>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Web/Views/AspNetRoles/Index.cshtml
@model IEnumerable<Web.Models.AspNetRoles>

@{
    ViewBag.Title = "Perfis de  usuários";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.MenuAtual = "PerfilDeUsuario";
}

<h2>Perfils de  usuários</h2>
<hr />
@using (Ajax.BeginForm("Index", "AspNetRoles", new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divListaRoles" }))
{
    <div class="container">
        <div class="row">
            <div class="col col-lg-12">
                @Html.Label("Pesquisar por nome:")
                @Html.TextBox("Pesquisar")
                <button type="submit" class="btn btn-info">
                    <span class="glyphicon glyphicon-search"></span> Pesquisar
                </button>
            </div>
        </div>
    </div>
}
<p>
    <a href="/AspNetRoles/Create" class="btn btn-primary btn-success"><span class="glyphicon glyphicon-plus"></span> Novo perfil</a>
</p>
@Html.Partial("_AspNetRoles", Model)

Web/Web/Views/AspNetRoles/_AspNetRoles.cshtml
@model IEnumerable<Web.Models.AspNetRoles>
<div id="divListaRoles">
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayName("Descrição")
            </th>
            <th>Ações</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a href="/AspNetRoles/Edit/@item.Id" class="btn btn-primary btn-primary">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Editar
                    </a>
                    <a href="/AspNetRoles/Delete/@item.Id" class="btn btn-primary btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                        Excluir
                    </a>
                </td>
            </tr>
        }

    </table>
</div>